# Generated by Django 5.0 on 2023-12-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeanimals', '0002_animalbreed_animal_animal_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(default='Кличка животного', max_length=100),
        ),
    ]
